language: java	
jobs:	
  include:	
    - stage: test	
      script: ./mvnw test	
    - stage: deploy to production
      script: skip
      deploy: &heroku
        provider: heroku
        app: fitness-freaks
        api_key: fb526d89-bf70-4c15-a394-49a5f34fdfe3
    - stage: test production
      script: 'curl http://fitness-freaks.herokuapp.com'
