language: java
jobs:
  include:
    - stage: first
      script: ./mvnw test -B
    - stage: second
      script: ./mvnw test
    - stage: third
      script: ./mvnw -Dtest=FitnessFreaksApplicationTests test
