spring:
    datasource:
        url: jdbc:mysql://db4free.net/fitness_db
        username: fitness_freaks
        password: Contador12

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect


    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 91351704026-5i311ll82ksbkfghas8665mniqses7io.apps.googleusercontent.com
              clientSecret: LoqDi3oi2Q3zoW5PYK4ioyB7
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - https://fitness-freaks.herokuapp.com/oauth2/redirect
      - http://localhost:8080/oauth2/redirect
